package udemy.oop_part_one;

import udemy.oop_part_one.geometricshapes.three_dimensional_shapes.Cuboid;
import udemy.oop_part_one.geometricshapes.two_dim_shapes.Circle;
import udemy.oop_part_one.geometricshapes.three_dimensional_shapes.Cylinder;
import udemy.oop_part_one.geometricshapes.two_dim_shapes.Rectangle;
import udemy.oop_part_one.carpet_cost_calc.Calculator;
import udemy.oop_part_one.carpet_cost_calc.Carpet;
import udemy.oop_part_one.carpet_cost_calc.Floor;

public class TestCodeImplementation {
    public static void main(String[] args) {
        Rectangle rectangle = new Rectangle(5, 10);
        System.out.println("rectangle width = " + rectangle.getWidth());
        System.out.println("rectangle length = " + rectangle.getLength());
        System.out.println("rectangle area = " + rectangle.getArea());
        Cuboid cuboid = new Cuboid(5, 10, 5);
        System.out.println("cuboid width = " + cuboid.getWidth());
        System.out.println("cuboid length = " + cuboid.getLength());
        System.out.println("cuboid area = " + cuboid.getArea());
        System.out.println("cuboid height = " + cuboid.getHeight());
        System.out.println("cuboid volume = " + cuboid.getVolume());
        Circle circle = new Circle(3.75);
        System.out.println("circle.radius = " + circle.getRadius());
        System.out.println("circle.area = " + circle.getArea());
        Cylinder cylinder = new Cylinder(5.55, 7.25);
        System.out.println("cylinder.radius = " + cylinder.getRadius());
        System.out.println("cylinder.height = " + cylinder.getHeight());
        System.out.println("cylinder.area = " + cylinder.getArea());
        System.out.println("cylinder.volume = " + cylinder.getVolume());
        ComplexNumber complexNumberOne = new ComplexNumber(1.0, 1.0);
        ComplexNumber complexNumberTwo = new ComplexNumber(2.5, -1.5);
        complexNumberOne.add(1,1);
        System.out.println("complexNumberOne.real = " + complexNumberOne.getReal());
        System.out.println("complexNumberOne.imaginary = " + complexNumberOne.getImaginary());
        complexNumberOne.subtract(complexNumberTwo);
        System.out.println("complexNumberOne.real = " + complexNumberOne.getReal());
        System.out.println("complexNumberOne.imaginary = " + complexNumberOne.getImaginary());
        complexNumberTwo.subtract(complexNumberOne);
        System.out.println("complexNumberTwo.real = " + complexNumberTwo.getReal());
        System.out.println("complexNumberTwo.imaginary = " + complexNumberTwo.getImaginary());
        Carpet carpetOne = new Carpet(3.5);
        Carpet carpetTwo = new Carpet(1.5);
        Floor floorOne = new Floor(2.75, 4.0);
        Floor floorTwo = new Floor(5.4, 4.5);
        Calculator calculatorOne = new Calculator(floorOne, carpetOne);
        Calculator calculatorTwo = new Calculator(floorTwo, carpetTwo);
        System.out.println("total cost to carpet floorOne: " + calculatorOne.getTotalCost());
        System.out.println("total cost to carpet floorTwo: " + calculatorTwo.getTotalCost());
        Point pointOne = new Point(6, 5);
        Point pointTwo = new Point(3, 1);
        Point pointThhree = new Point();
        System.out.println("distance(0,0)= " + pointOne.distance());
        System.out.println("distance(second)= " + pointOne.distance(pointTwo));
        System.out.println("distance(2,2)= " + pointOne.distance(2, 2));
        System.out.println("distance()= " + pointThhree.distance());
        SumCalculator sumCalculator = new SumCalculator();
        sumCalculator.setFirstNumber(5.0);
        sumCalculator.setSecondNumber(4);
        System.out.println("add= " + sumCalculator.getAdditionResult());
        System.out.println("subtract= " + sumCalculator.getSubtractionResult());
        sumCalculator.setFirstNumber(5.25);
        sumCalculator.setSecondNumber(0);
        System.out.println("multiply= " + sumCalculator.getMultiplicationResult());
        System.out.println("divide= " + sumCalculator.getDivisionResult());
        Person person = new Person();
        person.setFirstName("");
        person.setLastName("");
        person.setAge(10);
        System.out.println("fullName " + person.getFullName());
        System.out.println("teen= " + person.isTeen());
        person.setFirstName("John");
        person.setAge(18);
        System.out.println("fullName " + person.getFullName());
        System.out.println("teen= " + person.isTeen());
        person.setLastName("Smith");
        System.out.println("fullName " + person.getFullName());
        BankAccount bankAccount = new BankAccount();
        bankAccount.setEmail("gifty@juu.com");
        bankAccount.setBalance(10.00);
        bankAccount.depositFunds(9.00);
        bankAccount.withdrawFunds(3.97);
        VipCustomer vipCustomer1 = new VipCustomer();
        System.out.println(vipCustomer1.getName());
        VipCustomer vipCustomer2 = new VipCustomer("Bob",20.09);
        System.out.println(vipCustomer2.getName());
        VipCustomer vipCustomer3 = new VipCustomer("Jude", 329.78, "aboniious@gmail.com");
        System.out.println(vipCustomer3.getName());
        Wall wall = new Wall(5,4);
        System.out.println("Area: " + wall.getArea());
        wall.setHeight(-1.5);
        System.out.println("width: " + wall.getWidth());
        System.out.println("height: " + wall.getHeight());
        System.out.println("area: " + wall.getArea());
    }
}
